import { Sports } from '@response/typings';
import { LineOdds } from '../../models/line-odds';

export const lineOddsMapped: LineOdds = {
  oddsOfferOrder: ['MONEYLINE', 'SPREAD', 'OVER_UNDER'],
  sport: Sports.BASEBALL,
  bestOffer: {
    lines: [
      {
        moneySportsBookName: 'DraftKings',
        moneyline: -435,
        moneylineBest: false,
        moneylineUrl: 'https://go.metabet.io/bet/490598/draftkings',
        overUnder: 207.5,
        overUnderBest: false,
        overUnderOdds: -110,
        overUnderSportsBookName: 'BetMGM',
        overUnderUrl: 'https://go.metabet.io/bet/490598/mgm',
        spread: -9,
        spreadBest: false,
        spreadOdds: -110,
        spreadSportsBookName: 'DraftKings',
        spreadUrl: 'https://go.metabet.io/bet/490598/draftkings',
      },
      {
        moneySportsBookName: 'SI Sportsbook',
        moneyline: 375,
        moneylineBest: false,
        moneylineUrl: 'https://go.metabet.io/bet/490598/sport_888',
        overUnder: 208.5,
        overUnderBest: false,
        overUnderOdds: -110,
        overUnderSportsBookName: 'DraftKings',
        overUnderUrl: 'https://go.metabet.io/bet/490598/draftkings',
        spread: 9,
        spreadBest: false,
        spreadOdds: -110,
        spreadSportsBookName: 'DraftKings',
        spreadUrl: 'https://go.metabet.io/bet/490598/draftkings',
      },
    ],
  },
  competitors: [
    {
      id: 10207,
      name: 'Miami Heat',
    },
    {
      id: 10196,
      name: 'Detroit Pistons',
    },
  ],
  players: [],
  sportsBooks: [
    {
      name: 'SI Sportsbook',
      lines: [
        {
          moneyline: -500,
          moneylineBest: false,
          overUnder: 207.5,
          overUnderBest: false,
          overUnderOdds: -110,
          spread: -9.5,
          spreadBest: false,
          spreadOdds: -110,
        },
        {
          moneyline: 375,
          moneylineBest: true,
          overUnder: 207.5,
          overUnderBest: false,
          overUnderOdds: -110,
          spread: 9.5,
          spreadBest: false,
          spreadOdds: -110,
        },
      ],
      redirectUrl: 'https://go.metabet.io/bet/490598/sport_888',
    },
    {
      name: 'DraftKings',
      lines: [
        {
          moneyline: -435,
          moneylineBest: true,
          overUnder: 208.5,
          overUnderBest: false,
          overUnderOdds: -110,
          spread: -9,
          spreadBest: true,
          spreadOdds: -110,
        },
        {
          moneyline: 330,
          moneylineBest: false,
          overUnder: 208.5,
          overUnderBest: true,
          overUnderOdds: -110,
          spread: 9,
          spreadBest: true,
          spreadOdds: -110,
        },
      ],
      redirectUrl: 'https://go.metabet.io/bet/490598/draftkings',
    },
    {
      name: 'Fanduel',
      lines: [
        {
          moneyline: -480,
          moneylineBest: false,
          overUnder: 207.5,
          overUnderBest: false,
          overUnderOdds: -112,
          spread: -9.5,
          spreadBest: false,
          spreadOdds: -114,
        },
        {
          moneyline: 370,
          moneylineBest: false,
          overUnder: 207.5,
          overUnderBest: false,
          overUnderOdds: -108,
          spread: 9.5,
          spreadBest: false,
          spreadOdds: -106,
        },
      ],
      redirectUrl: 'https://go.metabet.io/bet/490598/fanduel',
    },
    {
      name: 'BetMGM',
      lines: [
        {
          moneyline: -455,
          moneylineBest: false,
          overUnder: 207.5,
          overUnderBest: true,
          overUnderOdds: -110,
          spread: -9.5,
          spreadBest: false,
          spreadOdds: -110,
        },
        {
          moneyline: 340,
          moneylineBest: false,
          overUnder: 207.5,
          overUnderBest: false,
          overUnderOdds: -110,
          spread: 9.5,
          spreadBest: false,
          spreadOdds: -110,
        },
      ],
      redirectUrl: 'https://go.metabet.io/bet/490598/mgm',
    },
    {
      name: 'PointsBet',
      lines: [
        {
          moneyline: -450,
          moneylineBest: false,
          overUnder: 208,
          overUnderBest: false,
          overUnderOdds: -110,
          spread: -9.5,
          spreadBest: false,
          spreadOdds: -110,
        },
        {
          moneyline: 340,
          moneylineBest: false,
          overUnder: 208,
          overUnderBest: false,
          overUnderOdds: -110,
          spread: 9.5,
          spreadBest: false,
          spreadOdds: -110,
        },
      ],
      redirectUrl: 'https://go.metabet.io/bet/490598/pointsbet',
    },
    {
      name: 'SugarHouse',
      lines: [
        {
          spread: -9.5,
          spreadOdds: -112,
          moneyline: -480,
          overUnder: 208.5,
          overUnderOdds: -108,
          moneylineBest: false,
          overUnderBest: false,
          spreadBest: false,
        },
        {
          moneyline: 360,
          moneylineBest: false,
          overUnder: 208.5,
          overUnderOdds: -113,
          spread: 9.5,
          spreadOdds: -109,
          overUnderBest: false,
          spreadBest: false,
        },
      ],
      redirectUrl: 'https://go.metabet.io/bet/490598/sugar_house_nj',
    },
    {
      name: 'Unibet',
      lines: [
        {
          spread: -9.5,
          spreadOdds: -112,
          moneyline: -480,
          overUnder: 208.5,
          overUnderOdds: -108,
          moneylineBest: false,
          overUnderBest: false,
          spreadBest: false,
        },
        {
          spread: 9.5,
          spreadOdds: -109,
          moneyline: 360,
          overUnder: 208.5,
          overUnderOdds: -113,
          moneylineBest: false,
          overUnderBest: false,
          spreadBest: false,
        },
      ],
      redirectUrl: 'https://go.metabet.io/bet/490598/unibet',
    },
    {
      name: 'William Hill',
      lines: [
        {
          spread: -9.5,
          spreadOdds: -110,
          moneyline: -476,
          overUnder: 208,
          overUnderOdds: -110,
          moneylineBest: false,
          overUnderBest: false,
          spreadBest: false,
        },
        {
          spread: 9.5,
          spreadOdds: -110,
          moneyline: 360,
          overUnder: 208,
          overUnderOdds: -110,
          moneylineBest: false,
          overUnderBest: false,
          spreadBest: false,
        },
      ],
      redirectUrl: 'https://go.metabet.io/bet/490598/william_hill',
    },
    {
      name: 'WynnBET',
      lines: [
        {
          spread: -9.5,
          spreadOdds: -110,
          moneyline: -455,
          overUnder: 208,
          overUnderOdds: -110,
          moneylineBest: false,
          overUnderBest: false,
          spreadBest: false,
        },
        {
          moneyline: 360,
          overUnder: 208,
          overUnderOdds: -110,
          spread: 9.5,
          spreadOdds: -110,
          moneylineBest: false,
          overUnderBest: false,
          spreadBest: false,
        },
      ],
      redirectUrl: 'https://go.metabet.io/bet/490598/wynn',
    },
  ],
};
