name: CI
on:
  push:
    branches:
      - main
  pull_request:

jobs:
  main:
    runs-on: ubuntu-latest

    if: ${{ github.event_name != 'pull_request' }}

    steps:
    - name: Checkout [main]
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - run: npm install
    - run: npm run test
    - run: npm run build:elements

    - name: Upload SDK as an artifact
      uses: actions/upload-artifact@v2
      with:
        name: snapodds-sdk
        path: dist/elements/snapodds/*

  pr:
    runs-on: ubuntu-latest

    if: ${{ github.event_name == 'pull_request' }}

    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        ref: ${{ github.event.pull_request.head.ref }}
        fetch-depth: 0

    - run: npm install
    - run: npm run test
    - run: npm run build:elements
